[package]
name = "tyange-cms-api"
version = "0.1.0"
edition = "2021"

[dependencies]
bcrypt = "0.17.0"
chrono = "0.4.40"
dotenv = "0.15.0"
jsonwebtoken = "9.3.1"
poem = { version = "3.1.7", features = [
    "multipart",
    "static-files",
] }
serde = { version = "1.0.219", features = [
    "derive",
] }
serde_json = "1.0.140"
sqlx = { version = "0.8.3", features = [
    "sqlite",
    "runtime-tokio",
] }
tokio = { version = "1.44.1", features = [
    "rt-multi-thread",
] }

[dependencies.uuid]
version = "1.16.0"
# Lets you generate random UUIDs
features = [
    "v4",
]
