name: Rust
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      skip_tests:
        description: "Skip tests"
        required: false
        default: false
        type: boolean
      deploy_only:
        description: "Deploy only (skip build)"
        required: false
        default: false
        type: boolean
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file
        run: |
          echo JWT_ACCESS_SECRET=${{ secrets.JWT_ACCESS_SECRET }} > .env
          echo JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} >> .env
          echo UPLOAD_PATH=${{ secrets.UPLOAD_PATH }} >> .env
      - name: Build
        if: ${{ !inputs.deploy_only }}
        run: cargo build --release --verbose
      - name: Run tests
        if: ${{ !inputs.skip_tests && !inputs.deploy_only }}
        run: cargo test --verbose
      - name: Stop service
        run: sudo systemctl stop tyange-cms-backend.service
      - name: Prepare upload directory
        run: |
          mkdir -p ${{ secrets.UPLOAD_PATH }}
          sudo chown -R $USER:$USER ${{ secrets.UPLOAD_BASE_PATH }}
          sudo chmod -R 755 ${{ secrets.UPLOAD_BASE_PATH }}/uploads
      - name: Move files to service location
        run: |
          mv target/release/tyange-cms-backend ${{ secrets.SERVICE_BINARY_PATH }}
          mv .env ${{ secrets.SERVICE_BINARY_PATH }}
      - name: Start service
        run: sudo systemctl start tyange-cms-backend.service
